#!/usr/bin/env bash
#
# Generates a wiki-formatted file from Karaf CLI command outputs.
# This script is part of the (unofficial) ONOS documentation toolset.
# 
# Assumed syntax is Confluence.
#
# TODO: generate HTML, and provide way to do individual commands.

set -o pipefail
IFS=$'\n'

TAB='&nbsp;&nbsp;&nbsp;&nbsp;'

function usage() {
cat << EOF

usage: $0 [ONOS instance]

required:
    [ONOS instance]   : the ONOS instance whose CLI to run against 

Outputs a 1) wiki-formatted file from Karaf CLI command outputs and
2) a list of Commands into a file named c2d_out.

Confluence wiki is not elegant about indentation, so expect a
bunch of &nbsp;'s.

EOF
}

# Formats the command into wiki syntax.
function fmtcmd() {
  local cmd=$1
  local cn=$(echo $cmd | awk '{split($0,a,":"); print a[2]}')

  # each command is Header3
  printf "\nh3. %s\n" "${cn}"

  # add font styles
  for i in $(onos $C2W_IN help $cmd); do
    printf "${TAB}"
    if [[ $i = DESCRIPTION || $i = SYNTAX ||
          $i = ARGUMENTS || $i = OPTIONS ]]; then
      printf "*%s*\n" "${i}"
    else 
      # bold things that begin with -, --, and are single words indented once.
      local l=$(echo $i | grep '^ \{8\}[a-zA-Z-]' | grep -v onos:)
      [ "$l" ] && local str="*${i}*"
      
      # identation and printing
      if [ "$l" ]; then
        printf "${str}\n" | sed -e 's:\(^\* \{8\}\)-:\1\\-:' -e 's: :\&nbsp;:g'
      else
        printf "${i}\n" | sed -e 's:\[:\\[:g' -e 's: :\&nbsp;:g' -e 's:	:'${TAB}${TAB}':g'
      fi
    fi
  done
}

if [ "$1" = "-h" ] || [ -z "$1" ]; then
  usage >&2 && exit
fi


# The ONOS instance to interrogate
C2W_IN=${1}
# Output file name
C2W_OUT="c2d_out"

#toc
printf "%s\n\n" '{toc:printable=true|style=none|maxLevel=3|type=flat|outline=true|separator=brackets|include=.*}' >> ${C2W_OUT}

onos ${C2W_IN} help onos | grep -v COMMANDS | awk '{print $1}' | while read command; do
  printf "."
  fmtcmd $command >> ${C2W_OUT}
done

printf "done.\n"

